name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - id: release
        uses: google-github-actions/release-please-action@v3.7.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          include-v-in-tag: true
