name: Test my custom actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-gen-access:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Generate access token
        id: generate_token
        uses: ./gen-access
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - run: node --eval "assert('${{ steps.generate_token.outputs.token }}'.length > 0);"
  test-setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js
        id: setup-node
        uses: ./setup-node
        with:
          node-version-file: .tool-versions
      - run: node --eval "assert('${{ steps.setup-node.outputs.package-manager }}' === 'pnpm');"
  test-turbo-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v2.0.0
        with:
          node-version-file: .tool-versions
      - run: cd turbo-cache && pnpm test
