name: Test my custom actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Setup Node.js
        id: setup-node
        uses: ./setup-node
        with:
          node-version-file: .tool-versions
      - run: node --eval "assert('${{ steps.setup-node.outputs.package-manager }}' === 'pnpm');"
  test-turbo-cache:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./turbo-cache
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@09dc95453afcf31d95905a8ec2eb3573a959dc9e # v3.7.6
        with:
          node-version-file: .tool-versions
      - run: pnpm i --frozen-lockfile
      - run: pnpm test
