name: Test my custom actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Setup Node.js
        id: setup-node
        uses: ./setup-node
        with:
          node-version-file: .tool-versions
      - run: node --eval "assert('${{ steps.setup-node.outputs.package-manager }}' === 'pnpm');"
  test-turbo-cache:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./turbo-cache
    steps:
      - uses: actions/checkout@v4.1.6
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.6.0
        with:
          node-version-file: .tool-versions
      - run: pnpm i --frozen-lockfile
      - run: pnpm test
